export const types = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
    ADD_TO_SHOPPING_CART: 'ADD_TO_SHOPPING_CART',
    REMOVE_FROM_SHOPPING_CART: 'REMOVE_FROM_SHOPPING_CART',
    UPDATE_AMOUNT_TO_SHOPPING_CART: 'UPDATE_AMOUNT_TO_SHOPPING_CART',
}