INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Casa de Tierra y Sangre' , 'Unidos por la sangre. Tentados por el deseo. Liberados por el destino. Llega la nueva saga de Sarah J. Maas... Bryce Quinlan tenía la vida perfecta, trabajando cada día y saliendo cada noche, hasta que un demonio asesinó a sus amigos y la dejó vacía, herida y sola. Cuando el acusado está entre rejas, pero los crímenes continúan, Bryce hará lo que sea para vengar sus muertes. Hunt Athalar es un ángel caído, esclavo de los arcángeles a los que una vez intentó destronar. Sus brutales habilidades sirven ahora para un solo propósito: acabar con los enemigos de su dueño. Pero entonces Bryce le ofrece un trato irresistible: si la ayuda a encontrar al demonio asesino, su libertad estará al alcance de su mano. Mientras Bryce y Hunt investigan en las entrañas de Ciudad Medialuna, descubren dos cosas: un poder oscuro que amenaza todo lo que desean proteger# y una atracción feroz que podría liberarlos a ambos. Con personajes inolvidables, un romance apasionado y una trama llena de suspense, la nueva novela de la autora bestseller Sarah J. Maas te sumergirá en una historia sobre el dolor de la pérdida, el precio de la libertad y el poder del amor.', 2021, 'Sarah J. Maas', 'Alfaguara'
, 2000, 40, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Educación En Pandemia
' , 'Hola. A ver si me manda un poquito menos de tarea para Julieta. Disculpame, pero yo no puedo estar más con esto. Tengo que estar encima de Julieta y de mi hijo de jardín de 5 años que también tiene un grupo que le manda a hacer un montón de pavadas. Tengo a Daniel. Tengo mis tres hijos y una casa que tengo que atender. Yo no puedo más con todo esto. Me está volviendo loca». La crisis de la pandemia de Covid-19 estalló en la educación con el cierre de los edificios escolares. Muy pronto quedó claro que grandes cantidades de estudiantes y también de docentes no tenían acceso a dispositivos tecnológicos y conectividad de calidad. Que teniéndolos, no era sencillo ponerse en marcha. Y que estábamos muy lejos del desafío que implica enseñar y aprender con las escuelas, los institutos y las universidades cerrados. En este libro, Mariana Maggio aborda la pregunta urgente “¿Y ahora qué hacemos?” en tres tiempos. Primero se asoma a las escenas de 2020 para reconocer allí lo que sucedió y las lecciones que sí se aprendieron. Luego, desarrolla un marco para abordar la educación en pandemia que, buscando superar visiones dicotómicas, pone la mirada en los cambios culturales que exigen revisar los modos de pensar y hacer la enseñanza. Y finaliza con una guía orientada a una acción educativa que sea, además, un puente a la transformación colectiva.', 2021, 'Mariana Maggio', 'Paidós'
, 5000, 10, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('La Sociedad Paliativa
' , 'En este ensayo, Byung-Chul Han critica como el exceso de positividad de la felicidad nos obliga a desbancar cualquier atisbo de dolor y nos somete en un estado de anestesia permanente.En la actualidad vivimos en una sociedad que ha desarrollado una fobia al dolor, en la que ya no hay lugar para el sufrimiento. Este miedo generalizado se refleja tanto en lo personal como lo social, e incluso en la política. El imperativo neoliberal «sé feliz», que esconde una exigencia de rendimiento, intenta evitar cualquier estado doloroso y nos empuja a un estado de anestesia permanente. Como en La sociedad del cansancio, Byung-Chul Han parte del supuesto de que en Occidente se ha producido un cambio radical de paradigma. Las sociedades premodernas tenían una relación muy íntima con el dolor y la muerte, que enfrentaban con dignidad y resignación. Sin embargo, en la actualidad, la positividad de la felicidad desbanca a la negatividad del dolor, y se extiende al ámbito social. Al expulsar de la vida pública los conflictos y las controversias, que podrían provocar dolorosas confrontaciones, se instaura una posdemocracia, que es en el fondo una democracia paliativa.ENGLISH:In this essay, Byung-Chul Han criticizes how the excess positivity of happiness forces us to negate any glimpse of pain and subjects us to a state of permanent anesthesia.Today we live in a society that has developed a phobia of pain, in which there is no longer room for suffering. This widespread fear is reflected both personally and socially, and even in politics. The neoliberal imperative ""be happy"", which hides a demand for performance, tries to avoid any painful state and pushes us into a state of permanent anesthesia. As he reflects in The Society of Tiredness, Byung-Chul Han is part of the assumption that there has been a radical paradigm shift in the West. Premodern societies had a very intimate relationship with pain and death, which they faced with dignity and resignation. Today, however, the positivity of happiness surpasses the negativity of pain, and extends to the social sphere. By expelling from public life conflicts and controversies, which could lead to painful confrontations, a post-democracy is established, which is at heart a palliative democracy.', 2021, 'Byung-Chul', 'Herder'
, 2000, 40, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Antimateria, Magia y Poesía' , 'En su nuevo libro, Andrés Gomberoff y José Edelstein reúnen un conjunto de veintitrés ensayos que se ofrecen como un muestrario, insuficiente pero necesario, de pequeñas joyas, hitos inverosímiles, momentos estelares que pueblan la construcción de la más humana de las actividades: la ciencia. Luego del éxito de Einstein para perplejos, esta nueva colaboración pretende celebrar aquellos instantes en los que la exploración científica se dejó llevar por una visión poética e integradora del cosmos, sea a través de la serena elegancia de la geometría o del proceloso torrente de la intuición.', 2021, 'Andrés Gomberoff, José Edelstein', 'Debate'
, 5000, 80, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Volcanes y Terremotos
' , 'Farías dirige el Depto. de obras civiles y geología de la Universidad Católica de Temuco. Desde el twitter y las columnas en La Tercera ha hecho una labor de divulgación que se recoge en esta crónica, la que aborda la historia y el comportamiento de volcanes y terremotos en Chile, tanto para el análisis de desastres pasados como también la previsión de eventos futuros, y la relación de estos fenómenos naturales con la población y sus ciudades.', 2021, 'Cristián Farías', 'B'
, 2000, 40, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('El Secreto de las Nubes' , 'Yuri nació con una extraña enfermedad cardiaca y está condenado a vivir recluido en su cuar- to, no puede convivir con otros niños ni ir a la escuela. Los doctores creen que su padecimiento está relacionado con el accidente de Chernóbil. Sus padres, una pareja de artistas ucranianos que abandonó su país tras el desastre nuclear, le procuran una profesora privada, Maggie, una joven neoyorquina que decidió dejar su exitosa carrera en Wall Street por una vida tranquila en Long Island. Pronto ambos forjan una profunda conexión, donde la curiosidad ilimitada y el optimismo excepcional de Yuri inspirarán a Maggie para realizar cambios difíciles en su propia vida y encontrar la fuerza cuando más la necesita.', 2021, 'Alyson Richman', 'Planeta'
, 6600, 430, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Sexo Inteligente. Manual de Sexualidad Para Adolescentes' , 'A modo de cuestionario pregunta-respuesta, la ginecóloga Andrea Huneeus aborda los tópicos de sexualidad por los que más le preguntan en consulta. Aborda desde los cambios físicos en la pubertad hasta temáticas urgentes de discutir como el consentimiento en el sexo, el autoconocimiento sexual, el abuso y las enfermedades de transmisión sexual.', 2020, 'Andrea Huneeus', 'Vergara'
, 10000, 10, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Código Nueva York', 'El exagente secreto Alberto Prat vuelve a ponerse a las órdenes del Vaticano para resolver el enigma detrás de una reliquia protegida hace años por los jesuitas y que ahora lo vuelve a poner en peligro a él junto a sus amigos más cercanos. La historia parte en Nueva York, donde tras la pandemia Prat, más viejo y cansado, se ve envuelto el crimen de un famoso millonario chileno y tendrá que enfrentar a un peligroso grupo de sicarios de alto nivel que están dispuestos a todo para conseguir unos antiguos documentos ligados a Isaac Newton y a la masonería. Desde tiroteos en el metro de Nueva York hasta persecuciones en el sur de Chile, son parte de una trama que también nos lleva al pasado, a la época del montonero Vicente Benavides entre 1813 y 1822 y su obsesión por una antigua reliquia cristiana que podría estar oculta en algún lugar de la provincia de Arauco.', 2021, 'Carlos Basso', 'Suma De Letras'
, 1000, 10, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Bridgerton: Felices Para Siempre' , 'Érase una vez una autora de romance histórico que creó una familia… Pero no cualquier familia. Ocho hermanos y hermanas, sus consortes, hijos e hijas, sobrinos y sobrinas, y también a una matriarca adorable e irreprimible… Son los Bridgerton, no una simple familia, sino una auténtica fuerza de la naturaleza. A lo largo de ocho novelas de gran éxito, los lectores y lectoras han reído, llorado y se han enamorado con sus historias. Pero querían más. Así que muchos preguntaron a la autora: ¿Qué ocurre luego? ¿Acaba Simon leyendo las cartas de su padre? ¿Francesca y Michael se convierten en padres? ¿Realmente “el final” tiene que ser el final? La obra que todos los amantes de esta fascinante saga estaban esperando.', 2021, 'Julia Quinn', 'Titania'
, 32000, 10, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('La Unidad Popular y la Revolución en Chile' , 'Hablar de la Unidad Popular desde lo que ella representó para las grandes mayorías, con sus búsquedas, pasiones y contradicciones, es hablar de uno de los momentos más luminosos para las y los humildes de nuestra historia. Son ellxs los protagonistas de esa historia y de este libro, por lo cual éste no es solo un relato histórico de la Unidad Popular: es también un relato gráfico, visual e interactivo en el que se conjugan escritura, fotografías, documentos, música, filmes a través de códigos QR, que permitirán ampliar la mirada sobre dicho proceso.', 2021, 'Mario Garcés', 'Lom', 40000, 30, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Los Sonidos de mi Cuerpo' , 'Cada día nuestro cuerpo emite sonidos voluntarios e involuntarios. Este divertido libro responde a los misterios de todos aquellos sonidos de nuestro organismo. Cada... Leer másCada día nuestro cuerpo emite sonidos voluntarios e involuntarios. Este divertido libro responde a los misterios de todos aquellos sonidos de nuestro organismo. Cada día hablamos, nos reímos, lloramos... ¿Por qué nuestro cuerpo a veces «habla» solo y no lo podemos controlar? Para entender nuestro cuerpo un poco mejor, en este libro encontraremos respuestas y también ingeniosos experimentos', 2014, 'Marta Maruszczak', 'Lata De Sal Editorial S.L.'
, 50000, 67, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Agujeros Negros' , 'El primer libro del científico Fernando Izaurieta es un viaje hacia los agujeros negros, feroces monstruos de espacio y tiempo. Usando el pensamiento científico, su relato nos lleva desde el inicio del tiempo en el big bang hasta su destrucción en la singularidad de los agujeros negros. La ciencia, el método de la duda y el escepticismo, es la clave para descifrar los misterios del universo y, también, para descubrir cómo forjar un futuro para la humanidad aun en sus momentos de crisis. A través de un relato ágil, junto con ejemplos cotidianos y accesibles, en estas páginas podemos asomarnos al interior de los agujeros negros. Allí, las ideas de Albert Einstein y Stephen Hawking nos llevan a visualizar fenómenos tan violentos y extraños que hacen palidecer a las grandes obras de la ciencia ficción. Agujeros negros, destructores del tiempo nos muestra cómo la ciencia nos permite ir más allá de los límites de nuestra imaginación para comprender los lugares más desconocidos y apasionantes del cosmos', 2021, 'Fernando Izaurieta', 'Planeta'
, 65000, 76, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Tres Caminos A Tacna' , 'Rafael Mellafe se atreve a plantearnos en esta novela histórica, una temática ocultada por la rigurosa sociedad de la segunda mitad del siglo XIX y por lo mismo prácticamente desconocida. Siempre apegado al rigor histórico, nos da una mirada profunda a la acomodada y tradicional sociedad chilena, boliviana y peruana en los años inmediatamente previos a la Guerra del Pacífico, a sus valores y entorno cultural. La trama se comienza a hilvanar en Colchagua, Sucre y Cajamarca y nos llevará en, epopéyicos viajes por el mundo de la época a lugares cercanos como la capital de Chile y otros tan distantes como París, que en aquella época era el centro de la llamada “Belle Epoque” y que marcó el pulso cultural mundial en esos años. Nos sumerge en la primera y trascendente gran batalla de la Guerra del Pacífico, la Batalla de Tacna o Campo de la Alianza. Nos permite observar dicha acción bélica en una forma cruda y directa, dejando atrás los viejos paradigmas de “Tambores y cornetas”. Los virtuosos valores de humanismo, amor y solidaridad están presentes en el relato, pero también asoma el otro lado del ser humano, el odio, la maldad y venganza. Una novela imperdible que nos hará entender un poco más algunos aspectos que la historia tradicional ha procurado ocultar.', 2021, 'Rafael Mellafe Maturana', 'Legatum'
, 1000, 67, current_timestamp, current_timestamp);


INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Cautiverio Feliz' , 'resumen', 2021, 'Ignacio Tirapegui', 'Liberalia'
, 5400, 10, current_timestamp, current_timestamp);


INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Extraterrestre' , 'En octubre de 2017, científicos del observatorio Haleakala, en Hawái, detectaron un objeto interestelar en movimiento próximo a la Tierra. Primero fue catalogado de cometa, pero esta hipótesis fue descartada. Llamado Oumuamua, «mensajero» o «explorador» en hawaiano, finalmente fue catalogado como asteroide, si bien su forma y su comportamiento diferían del resto de los asteroides y cometas de nuestro sistema solar. Cuanto más lo observaban los científicos, más extraño les parecía. Cuando Avi Loeb, catedrático de Astronomía de Harvard, sugirió que Oumuamua era la evidencia de vida y tecnología extraterrestre en el espacio, se desató el que probablemente sea el debate científico más relevante en décadas. En este libro, Loeb presenta por primera vez su teoría al gran público y nos ofrece un fasci- nante viaje por el universo desde los orígenes del tiempo, del espacio y de la vida.', 2021, 'Avi Loeb', 'Planeta'
, 4500, 10, current_timestamp, current_timestamp);


INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Riusplay y el Hechizo de la Luna Llena' , 'Una noche de luna llena, mientras Rius entrena con Invictor para convertirse en un valiente caballero, es atacado por una manada de hombres lobo. íLa maldición de la luna llena ha cobrado a su primera y más importante víctima! Y la única manera de salvar su vida es haciendo un viaje a los confines de la tierra, acompañado por Mike, Trollino y Timba, para tener los ingredientes de la porción mágica que necesita.', 2021, 'Riusplay', 'Altea'
, 23330, 100, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Clásicos Infantiles: Robin Hood' , 'Sin resumen', 2016, 'Varios Autores', 'Planeta Junior'
, 10300, 100, current_timestamp, current_timestamp);


INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('La Bailarina de Auschwitz' , 'Eger tenía dieciséis años cuando los nazis invadieron su pueblo de Hungría y se la llevaron con el resto de su familia a Auschwitz. Al pisar el campo, sus padres fueron enviados a la cámara de gas y ella permaneció junto a su hermana, pendiente de una muerte segura. Pero bailar El Danubio azul para Mengele salvó su vida, y a partir de entonces empezó una nueva lucha por la supervivencia. Primero en los campos de exterminio, luego en la Checoslovaquia tomada por los comunistas y, finalmente, en Estados Unidos, donde acabaría convirtiéndose en discípula de Viktor Frankl. Fue en ese momento, tras décadas ocultando su pasado, cuando se dio cuenta de la necesidad de curar sus heridas, de hablar del horror que había vivido y de perdonar como camino a la sanación. Su mensaje es claro: tenemos la capacidad de escapar de las prisiones que construimos en nuestras mentes y podemos elegir ser libres, sean cuales sean las circunstancias de nuestra vida. «Este libro es un regalo para la humanidad. Una de esas historias únicas y eternas que nunca quieres terminar de leer y que te cambian la vida para siempre.» Desmond Tutu, premio Nobel de la Paz. La bailarina de Auschwitz Una inspiradora historia de valentía y supervivencia', 2021, 'Edith Eger', 'Planeta'
, 21000, 340, current_timestamp, current_timestamp);


INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Frontera sur' , 'Novela histórica ambientada en el siglo XIX (1835-1859) en Chile; la historia se enmarca en una época en que la naciente república de Chile y la nación mapuche mantenían una relación entre estados, a veces no exenta de roces, pero que en general se caracterizó por una sana y pacífica convivencia, con territorios y atribuciones claramente delimitados, en que fluían en forma normal las actividades comerciales y las relaciones políticas y militares. Gran relato de época que narra las aventuras de Pedro Borquez, un chileno en el Wallmapu, construido con rigor y que significa el debut de Guillermo Parvex, exitoso narrador de no ficción, en la novela.', 2021, 'Guillermo Parvex', 'Ediciones B'
, 56000, 33, current_timestamp, current_timestamp);


INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('El Temor de un Hombre Sabio' , 'Encuadernación: Cartoné con sobrecubiertaColección: ÉxitosSegundo libro de la Trilogía Crónica del asesino de reyes«Todo hombre sabio teme tres cosas: la tormenta en el mar, la noche sin luna y la ira de un hombre amable.» El segundo día de la historia de Kvothe. La esperada continuación de El nombre del viento, de Patrick Rothfuss.Amanece en la posada Roca de Guía. Es el segundo día, y un hombre se dispone a proseguir el relato de su vida. Su verdadera historia, la que únicamente él conoce, alejada de la leyenda que le han forjado los rumores, las conjeturas y los cuentos de taberna que han acabado convirtiéndole en un personaje mítico: Kvothe... músico, mendigo, ladrón, estudiante, mago, héroe y asesino. El nombre del viento, el primer día de la historia de Kvothe, se ha convertido en un fenómeno apoyado por lectores, libreros y crítica, que recomiendan esta excepcional novela. Ahora la historia sigue en El temor de un hombre sabio, y a aquellos que ansiaban leer esta continuación sólo podemos decirles que la espera ha valido la pena.', 2011, 'Patrick Rothfuss', 'Plaza & Janés'
, 23444, 56, current_timestamp, current_timestamp);


INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('El Extraño Caso del dr. Jekyll y mr. Hyde' , 'Robert Louis Stevenson fue uno de los gigantes de la novela de aventuras, pero también fue uno de los grandes conocedores de la mentalidad humana, por lo que era de rigor que tarde o temprano escribiera un clásico imperecedero como El extraño caso del doctor Jekyll y el señor Hyde (1886). Lúcido testigo de la Revolución Industrial ocurrida en el Reino Unido, Stevenson reflexiona acerca de los límites del método y de la ética científicos, pero, sobre todo y de una manera absorbente e inolvidable, de la dualidad entre el bien y el mal.', 2019, 'Robert Louis Stevenson', 'Alma'
, 500, 10, current_timestamp, current_timestamp);


INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Dímelo en Secreto' , 'Kami Hamilton tenía doce años cuando le dieron su primer beso: desde entonces los labios de Thiago Franco, el hermano de su mejor amigo, Taylor, la persiguen en sueños. Hace seis años que los dos hermanos desaparecieron de su vida sin dejar rastro... hasta ahora. Los hermanos han regresado y el mundo aparentemente perfecto de Kamilah se tambalea. Ella ya no es la niña inocente que conocieron: ahora es la más popular del instituto, donde la llaman «la reina de cristal» porque nunca deja entrever ningún sentimiento. Es perfecta y parece que nadie, ni siquiera su novio, puede acceder realmente a ella... Nadie excepto los hermanos Franco. ¿Podrá resistirse Kami a la simple presencia de Thiago? ¿La perdonará él por lo que sucedió cuando solo eran unos niños?', 2021, 'Mercedes Ron', 'Montena'
, 600, 30, current_timestamp, current_timestamp);


INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('El Gran Libro de los Supertesoros' , 'La familia, los recuerdos, los maestros, la naturaleza, los animales, los amigos, los sueños... Las cosas más importantes no son las materiales. Existen supertesoros muy valiosos que nos hacen felices y que debemos cuidar. ¿Cuáles son los tuyos?
', 2009, 'Susanna Isern', 'Flamboyant'
, 3400, 650, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('El Principio Vida: Hacia una Biología Filosófica (Estructuras y Procesos. Filosofía)' , 'Hans Jonas, cuyas publicaciones sobre antropología filosófica han dado en las últimas décadas un impulso fundamental a la discusión ideológica internacional, desarrolla en «El principio vida» una concepción del mundo orgánico que intenta superar la división entre lo intelectual y lo material (espíritu y materia), que desde Descartes es la base de las ciencias y la filosofía. Un análisis crítico, la descripción e interpretación filosóficas de las facultades y funciones orgánicas demuestra que «lo orgánico» preconfigura ya en sus formas más elementales «lo espiritual», y que el espíritu, aun en sus más elevadas expresiones, continúa siendo parte de lo orgánico. Llevado a la fórmula más escueta, este libro presenta una interpretación ontológica de fenómenos biológicos. La lectura filosófica del texto biológico puede recuperar la dimensión interna de la comprensión de los fenómenos orgánicos y así hacer que la unidad físico-psíquica de la vida regrese al lugar central en la totalidad teórica, que había perdido desde hace tiempo. El provecho para la comprensión de lo orgánico será así también un beneficio para la comprensión de lo humano.', 2000, 'Hans Jonas', 'Trotta'
, 27000, 50, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('El Quinto Elemento: Espionaje, Ciberguerra y Terrorismo. Una Amenaza Real e Inminente' , 'La tercera guerra mundial ha comenzado y todos somos soldados en las trincheras.Los clásicos hablaban de cuatro elementos: tierra, agua, fuego y aire, así como de un quinto invisible, el éter. Estos cuatro elementos son también las cuatro divisiones de los ejércitos, a los que ahora se añade un quinto elemento: el ciberespacio (también, como el éter, invisible y casi indetectable). Una nueva contienda mundial ha comenzado y todos somos soldados en las trincheras. El nuevo gran conflicto internacional trasciende todas las fronteras físicas y se libra simultáneamente en cientos de países. El nuevo escenario de la lucha son las redes digitales, el ciberespacio y el iceberg de la gran Internet oculta que no conocemos. Quien domine la información y la sociedad intrerconectada controlará el mundo. ¿Qué papel tienen en ello los gobiernos mundiales, con agencias como el CNI español o la NSA estadounidense? ¿Cómo aprovechan este nuevo escenario criminales y terroristas? ¿Qué papel tienen las empresas y cómo se aprovechan o se defienden de ellos, según los casos? ¿Puede un ataque informático sembrar el caos y provocar un desplome económico mundial? ¿Son tus datos sólo tuyos o hay quien puede utilizarlos en tu contra? Espionaje de las telecomunicaciones, control de las agencias gubernamentales a sus propios ciudadanos, ciberataques y competencia empresarial, ciberterrorismo, robo de secretos militares, sabotaje industrial. Los crímenes del futuro que ya están aquí y están siendo silenciados. Descubre la partida que se juega entre bambalinas, y cómo puedes protegerte y minimizar sus efectos, en un relato desasosegante, ante el cual sólo cabe reaccionar disponiendo de toda aquella información que, qué duda cabe, nos quieren ocultar y que Alejandro Suárez Sánchez-Ocaña desvela en este libro.', 2015, 'Alejandro Suárez Sánchez-Ocaña', 'Deusto'
, 22400, 10, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Adivina Quién soy (la Erótica)' , 'Yanira trabaja de cantante en los hoteles de Tenerife. Está soltera y vive rodeada de su familia. Su vida es plácida y, en cierto modo, acomodada.Pero a Yanira le gusta experimentar cosas nuevas, y decide adentrarse en el mundo de los intercambios de pareja. En uno de los bares que frecuenta conoce a un italiano que le enseñará que el sexo va mucho más allá de lo que ella conocía hasta el momento. Un año más tarde se traslada a Barcelona y comienza a trabajar de camarera en un crucero de vacaciones llamado Espíritu Santo. En el barco también está Dylan, un atractivo empleado de la sección de mantenimiento que apenas le hace caso, a pesar de las continuas sonrisas de Yanira. Lo que ella no sabe es que la observa más de lo que cree, y aunque los malentendidos que surgen entre ellos le hacen pensar lo contrario, la atracción que sienten les hará encontrarse y compartir un sinfín de juegos morbosos, divertidos y sensuales. Adivina quién soy es una divertida comedia erótica en la que las sonrisas brotarán a raudales de tu boca y donde tú misma te sentirás en la piel de la protagonista.', 2016, 'Megan Maxwell', 'FBooket'
, 14400, 20, current_timestamp, current_timestamp);


INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('La Guerra de los Mundos' , 'La vida se está extinguiendo en Marte. Una especie entera busca un nuevo planeta donde vivir. La Tierra es el lugar elegido. Pese a todos los esfuerzos de la resistencia terrícola, la invasión se lleva a cabo de forma eficaz. Los marcianos cuentan con alta tecnología. Pero no son inmunes a todo. Un inesperado obstáculo equilibrará las fuerzas...', 2009, 'H.G. Wells', 'Latinbooks'
, 3400, 120, current_timestamp, current_timestamp);

INSERT INTO public.books(
	name, resume, year, author, editorial, price, stock, "createdAt", "updatedAt")
	VALUES ('Pacifico. Historias de la Guerra' , 'La guerra contada desde su inicio, en 1879, hasta mucho tiempo des pués, cuando el mapa del continente ha cambiado y lo que ocurrió entre Chile, Perú y Bolivia es apenas un recuerdo difu so en el nuevo orden sudamericano del año 2081. Entre uno y otro punto se desarrollan las siete historias de este libro: aquí está la voz de los niños que participaron en las batallas más feroces antes de la entrada de las tropas chilenas a Lima y ta mbién las razones que tuvo un héroe naval para recluirse lejos de la gloria y del honor. Está el empeño de la armada por en contrar a un misterioso submarino peruano hundido en el Callao, la persistencia de la memoria en los relatos familiares so bre lo que realmente ocurrió en la campaña de la Sierra y, por último, la historia de dos estatuas separadas al final de la g uerra y su insospechado destino a uno y otro lado de la frontera. Pacífico convoca a escritores chilenos y peruanos de registros muy distint os que, invitados a recrear y reconstruir pasajes del conflicto, proponen miradas diversas aunque unidas por un elemento común: la herencia de una guerra que, pese a los años, aún no se termina de contar pues sacó lo mejor y lo peor de nuestr os países. Los siete relatos que componen esta antología abordan diversos esc enarios y momentos de la Guerra del Pacífico. Los autores convocados -Juan Carlos Cortázar, Juan Cristóbal Guarello, Patricio Jara, Alej andro Neyra, Alberto Rojas, Francisco Schilling y Carlos Tromben - se han propuesto recrear ciertos episodios significativos del con flicto, algunos ocurridos a poco del inicio o bien mucho tiempo después de firmada la paz. Son rela tos extensos, documentados, con personajes reales y situaciones que adquieren un matiz distinto gracias a este destaca do grupo de narradores chilenos y peruanos, capaces de mirar con lucidez aquel instante de nuestra historia y transformarla en literatura.', 2017, 'Varios Autores', 'Ediciones B'
, 10000, 32, current_timestamp, current_timestamp);